-- =========================================================================
-- Prompt Intelligence Engine Extensions (Migration 004)
-- Extends the generation_sessions and generation_prompts tables
-- =========================================================================

-- 1. Extend generation_sessions
ALTER TABLE generation_sessions
    ADD COLUMN business_id UUID REFERENCES brand_core_identity(business_id) ON DELETE CASCADE,
    ADD COLUMN creative_request JSONB,
    ADD COLUMN brand_brain_snapshot JSONB,
    ADD COLUMN model_name VARCHAR(100);

-- 2. Extend generation_prompts
ALTER TABLE generation_prompts
    ADD COLUMN structured_prompt JSONB;

-- Note: The existing 'prompt' column in generation_prompts will be used 
-- to store the 'optimized_prompt' generated by the PromptOptimizer.
